### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by BergerAPI**
I changed "insecurly" to "insecurely"

### CODE REVIEW

**Comment by paperdave** [comment]
thank you, did you do a pass through the rest of the docs for other misspellings?

also if you have this locally can you also run `pnpm changeset` to create changelog data. if not I'll do it myself before merging. can write a note such as "fixed jsdoc spelling errors".

**Comment by BergerAPI** [comment]
No problem. Sadly, I just noticed this one while checking out the project. I didn't check any other docs nor source files. I don't have the project locally either, so you would need to create the change-log data.

I may look for more issues in the future.

**Comment by paperdave** [comment]
alright, thanks. the changelog isn't a big deal since I have the repo locally with all the deps installed and so on.

**Comment by BergerAPI** [comment]
:+1:

**Pull request merged**
